# SPDX-License-Identifier: GPL-2.0

qnoc-msm8974-objs			:= msm8974.o
qnoc-qcs404-objs			:= qcs404.o
qnoc-sdm845-objs			:= sdm845.o
icc-smd-rpm-objs			:= smd-rpm.o
qnoc-sc7180-objs			:= sc7180.o
qnoc-sm8150-objs			:= sm8150.o
icc-rpmh-obj			:= icc-rpmh.o
bcm-voter-objs			:= bcm-voter.o

obj-$(CONFIG_INTERCONNECT_QCOM_MSM8974) += qnoc-msm8974.o
obj-$(CONFIG_INTERCONNECT_QCOM_QCS404) += qnoc-qcs404.o
obj-$(CONFIG_INTERCONNECT_QCOM_SDM845) += qnoc-sdm845.o
obj-$(CONFIG_INTERCONNECT_QCOM_SMD_RPM) += icc-smd-rpm.o
obj-$(CONFIG_INTERCONNECT_QCOM_SC7180) += qnoc-sc7180.o
obj-$(CONFIG_INTERCONNECT_QCOM_SM8150) += qnoc-sm8150.o
obj-$(CONFIG_INTERCONNECT_QCOM_RPMH) += icc-rpmh.o
obj-$(CONFIG_INTERCONNECT_QCOM_BCM_VOTER) += bcm-voter.o
