/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2020, The Linux Foundation. All rights reserved.
 */

#ifndef _DT_BINDINGS_CLK_QCOM_LPASS_CC_SM8550_H
#define _DT_BINDINGS_CLK_QCOM_LPASS_CC_SM8550_H

/* LPASS_CORE_CC */
#define LPASS_CORE_CC_CORE_CLK_SRC		0
#define LPASS_CORE_CC_SYSNOC_MPORT_CORE_CLK	1

/* LPASS_AUDIO_CC */
#define LPASS_AUDIO_CC_WSA_MCLK_CLK_SRC 	0
#define LPASS_AUDIO_CC_RX_MCLK_CLK_SRC 		1
#define LPASS_AUDIO_CC_WSA_MCLK_2X_CLK 		2
#define LPASS_AUDIO_CC_WSA_MCLK_CLK 		3
#define LPASS_AUDIO_CC_WSA2_MCLK_2X_CLK 	4
#define LPASS_AUDIO_CC_WSA2_MCLK_CLK 		5
#define LPASS_AUDIO_CC_RX_MCLK_2X_CLK 		6
#define LPASS_AUDIO_CC_RX_MCLK_CLK 		7

/* LPASS_AON_CC */
#define LPASS_AON_CC_TX_MCLK_CLK_SRC			0
#define LPASS_AON_CC_TX_MCLK_CLK			1

#define LPASS_AON_CC_LPASS_AUDIO_HM_GDSCR	0

/* LPASS_CORE_HM */
#define LPASS_CORE_HM_GDSCR				0

#endif
