/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2020, The Linux Foundation. All rights reserved.
 */

#ifndef _DT_BINDINGS_CLK_QCOM_LPASS_CC_SM8550_H
#define _DT_BINDINGS_CLK_QCOM_LPASS_CC_SM8550_H

/* LPASS_CORE_CC */
#define LPASS_CORE_CC_EXT_IF0_CLK_SRC		0
#define LPASS_CORE_CC_EXT_IF1_CLK_SRC		1
#define LPASS_CORE_CC_EXT_IF2_CLK_SRC		2
#define LPASS_CORE_CC_CORE_CLK_SRC		3
#define LPASS_CORE_CC_EXT_IF0_IBIT_CLK		4
#define LPASS_CORE_CC_EXT_IF1_IBIT_CLK		5
#define LPASS_CORE_CC_EXT_IF2_IBIT_CLK		6
#define LPASS_CORE_CC_SYSNOC_MPORT_CORE_CLK	7

/* LPASS_AUDIO_CC */
#define LPASS_AUDIO_CC_EXT_IF2_CLK_SRC 		0
#define LPASS_AUDIO_CC_WSA_MCLK_CLK_SRC 	1
#define LPASS_AUDIO_CC_RX_MCLK_CLK_SRC 		2
#define LPASS_AUDIO_CC_EXT_IF2_IBIT_CLK 	3
#define LPASS_AUDIO_CC_WSA_MCLK_CLK 		4
#define LPASS_AUDIO_CC_TX_MCLK_WSA_CLK 		5
#define LPASS_AUDIO_CC_RX_MCLK_CLK 		6
#define LPASS_AUDIO_CC_TX_MCLK_RX_CLK 		7
#define LPASS_AUDIO_CC_WSA2_MCLK_CLK 		8
#define LPASS_AUDIO_CC_TX_MCLK_WSA2_CLK 	9
#define LPASS_AUDIO_CC_CODEC_MEM_CLK 		10
#define LPASS_AUDIO_CC_CODEC_MEM0_CLK 		11
#define LPASS_AUDIO_CC_CODEC_MEM1_CLK 		12
#define LPASS_AUDIO_CC_CODEC_MEM2_CLK 		13
#define LPASS_AUDIO_CC_CODEC_MEM3_CLK 		14

/* LPASS_AON_CC */
#define LPASS_AON_CC_MAIN_CLK_SRC	0
#define LPASS_AON_CC_TX_MCLK_CLK_SRC	1
#define LPASS_AON_CC_VA_MEM0_CLK	2
#define LPASS_AON_CC_TX_MCLK_CLK	3

#define LPASS_AON_CC_LPASS_AUDIO_HM_GDSCR	0

/* LPASS_CORE_HM */
#define LPASS_CORE_HM_GDSCR				0

#endif
