// SPDX-License-Identifier: GPL-2.0

#ifndef _DT_BINDINGS_CLK_MSM_GCC_8917_H
#define _DT_BINDINGS_CLK_MSM_GCC_8917_H

#define GPLL0_VOTE 0
#define SDCC1_APPS_CLK_SRC 1
#define SDCC2_APPS_CLK_SRC 2
#define GCC_SDCC1_AHB_CLK 3
#define GCC_SDCC1_APPS_CLK 4
#define GCC_SDCC2_AHB_CLK 5
#define GCC_SDCC2_APPS_CLK 6
#define GCC_USB2A_PHY_SLEEP_CLK 7
#define GCC_USB_HS_PHY_CFG_AHB_CLK 8
#define USB_HS_SYSTEM_CLK_SRC 9
#define GCC_USB_HS_AHB_CLK 10
#define GCC_USB_HS_SYSTEM_CLK 11
#define CRYPTO_CLK_SRC 12
#define GCC_CRYPTO_AHB_CLK 13
#define GCC_CRYPTO_AXI_CLK 14
#define GCC_CRYPTO_CLK 15
#define GFX3D_CLK_SRC 16
#define GCC_OXILI_AHB_CLK 17
#define GCC_OXILI_GFX3D_CLK 18
#define GCC_BIMC_GFX_CLK 19
#define GCC_BIMC_GPU_CLK 20
#define BYTE0_CLK_SRC 21
#define PCLK0_CLK_SRC 22
#define ESC0_CLK_SRC 23
#define MDP_CLK_SRC 24
#define VSYNC_CLK_SRC 25
#define GCC_MDSS_AHB_CLK 26
#define GCC_MDSS_AXI_CLK 27
#define GCC_MDSS_BYTE0_CLK 28
#define GCC_MDSS_ESC0_CLK 29
#define GCC_MDSS_MDP_CLK 30
#define GCC_MDSS_PCLK0_CLK 31
#define GCC_MDSS_VSYNC_CLK 32
#define GCC_BLSP1_AHB_CLK 33
#define GCC_BLSP2_AHB_CLK 34
#define BLSP1_QUP3_I2C_APPS_CLK_SRC 35
#define BLSP2_QUP1_I2C_APPS_CLK_SRC 36
#define GCC_BLSP1_QUP3_I2C_APPS_CLK 37
#define GCC_BLSP2_QUP1_I2C_APPS_CLK 38
#define GCC_MSS_CFG_AHB_CLK 39
#define GCC_BOOT_ROM_AHB_CLK 40
#define GCC_MSS_Q6_BIMC_AXI_CLK 41
#define GCC_SMMU_CFG_CLK 42
#define GCC_APSS_TCU_CLK 43
#define GCC_GFX_TCU_CLK 44

/* Indexes for GDSCs */
#define VENUS_GDSC 0
#define VENUS_CORE0_GDSC 1
#define MDSS_GDSC 2
#define JPEG_GDSC 3
#define VFE_GDSC 4
#define VFE1_GDSC 5
#define CPP_GDSC 6
#define OXILI_GDSC 7

#endif
